# Generated by Django 4.1.5 on 2023-01-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperateSystem', models.CharField(max_length=150)),
                ('Activate', models.CharField(max_length=10)),
                ('CurrentUser', models.CharField(max_length=100)),
                ('MAC', models.CharField(max_length=100)),
                ('SystemName', models.CharField(max_length=50)),
                ('LANSpeed', models.CharField(max_length=10)),
                ('HDD', models.CharField(max_length=150)),
                ('Mboard', models.CharField(max_length=150)),
                ('ProcessorName', models.CharField(max_length=150)),
                ('Soccet', models.CharField(max_length=50)),
                ('OZU', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TypesEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypesEq', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('MidlName', models.CharField(max_length=100)),
                ('SurName', models.CharField(max_length=100)),
                ('Position_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.positions')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvNum', models.CharField(max_length=9)),
                ('Brand_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.brands')),
                ('Hardware_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.hardware')),
                ('Model_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.models')),
                ('Types_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.typesequipments')),
                ('Unit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.units')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.users')),
            ],
        ),
    ]
