# Generated by Django 4.1.5 on 2023-01-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0002_rename_position_id_users_position_users_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Units',
            new_name='Unit',
        ),
    ]
