# Generated by Django 4.1.5 on 2023-01-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0003_rename_positions_position_rename_units_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='Unit_id',
        ),
        migrations.AddField(
            model_name='hardware',
            name='InstalledSoft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='PrinterTypeConnect',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Hardware_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.hardware'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Activate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='CurrentUser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='HDD',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='LANSpeed',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='MAC',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Mboard',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='OZU',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='OperateSystem',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='ProcessorName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Soccet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='SystemName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='models',
            name='ModelName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='PositionName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='unit',
            name='UnitName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='Position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.position'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.unit'),
        ),
    ]
