# Generated by Django 4.1.5 on 2023-01-27 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0004_remove_equipments_unit_id_hardware_installedsoft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserName',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[0-9]', message='Wrong')]),
        ),
    ]
