# Generated by Django 4.1.5 on 2023-01-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0005_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.brands'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Hardware_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='input_data.hardware'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.models'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Types_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.typesequipments'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='input_data.position'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='input_data.unit'),
        ),
    ]
