# Generated by Django 4.1.5 on 2023-01-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0006_alter_equipments_brand_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvNumber', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='equipments',
            name='InvNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.invnum'),
        ),
    ]
