# Generated by Django 4.1.5 on 2023-01-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0007_invnum_alter_equipments_invnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='InvNum',
            new_name='Number',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='Brand_id',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='Model_id',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='Types_id',
        ),
        migrations.AddField(
            model_name='invnum',
            name='brand',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='input_data.brands'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invnum',
            name='model',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='input_data.models'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invnum',
            name='typ',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='input_data.typesequipments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipments',
            name='User_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='input_data.users'),
        ),
    ]
