# Generated by Django 4.1.5 on 2023-01-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0009_alter_brands_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invnum',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.brands'),
        ),
        migrations.AlterField(
            model_name='invnum',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.models'),
        ),
        migrations.AlterField(
            model_name='invnum',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.typesequipments'),
        ),
    ]
