# Generated by Django 4.1.5 on 2023-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0013_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='BrandName',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
