# Generated by Django 4.1.5 on 2023-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0014_alter_brands_brandname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invnum',
            name='InvNumber',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='ModelName',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='PositionName',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='typesequipments',
            name='TypesEq',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='UnitName',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
