# Generated by Django 4.1.5 on 2023-01-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0015_alter_invnum_invnumber_alter_models_modelname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='InvNumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='input_data.invnum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input_data.hardware'),
        ),
    ]
