# Generated by Django 4.1.5 on 2023-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_data', '0016_hardware_invnumber_alter_equipments_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='IPAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Activate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='CurrentUser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='HDD',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='InstalledSoft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='LANSpeed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='MAC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Mboard',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='OZU',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='OperateSystem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='PrinterTypeConnect',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='ProcessorName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Soccet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='SystemName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
